// <auto-generated />
using System;
using LunchOrganizer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LunchOrganizer.Data.Migrations
{
    [DbContext(typeof(LunchOrganizerDbContext))]
    [Migration("20260824112139_AddBookingPcUserColumns")]
    partial class AddBookingPcUserColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LunchOrganizer.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date")
                        .HasColumnName("booking_date");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset(7)")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CAST(SYSUTCDATETIME() AS datetimeoffset)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<int>("MenuId")
                        .HasColumnType("int")
                        .HasColumnName("menu_id");

                    b.Property<decimal>("PriceSnapshot")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price_snapshot");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset(7)")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CAST(SYSUTCDATETIME() AS datetimeoffset)");

                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(320)")
                        .HasColumnName("user_email");

                    b.Property<string>("UserFullName")
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("user_fullname");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("user_name");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("version")
                        .HasDefaultValueSql("1");

                    b.HasKey("Id");

                    b.HasIndex("BookingDate")
                        .HasDatabaseName("ix_bookings_booking_date");

                    b.HasIndex("EmployeeId", "BookingDate")
                        .IsUnique()
                        .HasDatabaseName("ix_bookings_employee_date");

                    b.HasIndex("MenuId", "BookingDate");

                    b.ToTable("bookings", null, t =>
                        {
                            t.HasCheckConstraint("ck_bookings_price_snapshot_non_negative", "price_snapshot >= 0");
                        });
                });

            modelBuilder.Entity("LunchOrganizer.Domain.Entities.DailyPrice", b =>
                {
                    b.Property<DateOnly>("PriceDate")
                        .HasColumnType("date")
                        .HasColumnName("price_date");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset(7)")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CAST(SYSUTCDATETIME() AS datetimeoffset)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset(7)")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CAST(SYSUTCDATETIME() AS datetimeoffset)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("version")
                        .HasDefaultValueSql("1");

                    b.HasKey("PriceDate");

                    b.ToTable("daily_prices", null, t =>
                        {
                            t.HasCheckConstraint("ck_daily_prices_price_non_negative", "price >= 0");
                        });
                });

            modelBuilder.Entity("LunchOrganizer.Domain.Entities.EmailLogEntry", b =>
                {
                    b.Property<DateOnly>("SummaryDate")
                        .HasColumnType("date")
                        .HasColumnName("summary_date");

                    b.Property<int>("BookingCount")
                        .HasColumnType("int")
                        .HasColumnName("booking_count");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error_message");

                    b.Property<string>("Recipients")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("recipients");

                    b.Property<DateTimeOffset>("SentAtUtc")
                        .HasColumnType("datetimeoffset(7)")
                        .HasColumnName("sent_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.HasKey("SummaryDate");

                    b.ToTable("email_log", (string)null);
                });

            modelBuilder.Entity("LunchOrganizer.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset(7)")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CAST(SYSUTCDATETIME() AS datetimeoffset)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("full_name")
                        .UseCollation("Latin1_General_CI_AS");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset(7)")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CAST(SYSUTCDATETIME() AS datetimeoffset)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("version")
                        .HasDefaultValueSql("1");

                    b.HasKey("Id");

                    b.HasIndex("FullName")
                        .IsUnique()
                        .HasDatabaseName("ix_employees_full_name");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("LunchOrganizer.Domain.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset(7)")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("CAST(SYSUTCDATETIME() AS datetimeoffset)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateOnly>("MenuDate")
                        .HasColumnType("date")
                        .HasColumnName("menu_date");

                    b.Property<int>("MenuNumber")
                        .HasColumnType("int")
                        .HasColumnName("menu_number");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset(7)")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CAST(SYSUTCDATETIME() AS datetimeoffset)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("version")
                        .HasDefaultValueSql("1");

                    b.HasKey("Id");

                    b.HasIndex("MenuDate")
                        .HasDatabaseName("ix_menus_menu_date");

                    b.HasIndex("MenuDate", "MenuNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_menus_menu_date_menu_number");

                    b.ToTable("menus", null, t =>
                        {
                            t.HasCheckConstraint("ck_menus_menu_number_positive", "menu_number >= 1");
                        });
                });

            modelBuilder.Entity("LunchOrganizer.Domain.Entities.Booking", b =>
                {
                    b.HasOne("LunchOrganizer.Domain.Entities.Employee", "Employee")
                        .WithMany("Bookings")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LunchOrganizer.Domain.Entities.Menu", "Menu")
                        .WithMany("Bookings")
                        .HasForeignKey("MenuId", "BookingDate")
                        .HasPrincipalKey("Id", "MenuDate")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("LunchOrganizer.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("LunchOrganizer.Domain.Entities.Menu", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
